PROJECT_NAME = 'Bplid-API'
VERSION = '0.1'


DATABASE_USER = 'postgres'
DATABASE_PASSWORD = 'admin'
DATABASE_NAME = 'db'
DATABASE_HOST = 'localhost:5432'

DATABASE_URL = f'postgresql://{DATABASE_USER}:{DATABASE_PASSWORD}@{DATABASE_HOST}/{DATABASE_NAME}'
